### ISSUE TITLE
"ValueError: need more than 1 value to unpack" Error. Can anyone help?

### ISSUE THREAD

**Issue by maiiDeep** [MarvinTeichmann/KittiSeg#101]
Hi ,
I got this error while running in 7 core CPU, 16GM RAM engine. I could not follow "ValueError: need more than 1 value to unpack". I would appreciate any help if given reason and most possible solution.

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/lab1/KittiSeg/hypes/../inputs/kitti_seg_input.py", line 350, in enqueue_loop
    for d in gen:
  File "/home/lab1/KittiSeg/hypes/../inputs/kitti_seg_input.py", line 155, in _make_data_gen
    for image, gt_image in data:
  File "/home/lab1/KittiSeg/hypes/../inputs/kitti_seg_input.py", line 114, in _load_gt_file
    image_file, gt_image_file = file.split(" ")
ValueError: need more than 1 value to unpack

**Comment by villanuevab** [comment]
What do the contents of your `data_file` look like? The error implies that the lines in your `data_file` contain a string without spaces, e.g., 
```
somestringwithoutspaces1
somestringwithoutspaces2
...
```
The function expects a `data_file` that has lines that look like: 
```
image1_filename gt_image1_filename
image2_filename gt_image2_filename
...
```
`image1_filename` and `gt_image1_filename` should correspond to the paths in your file system to the input and label images to be trained on, respectively. This part of the code in `kitti_seg_input.py` should identify where the images and label images are located in you file system / on disk.

Hope this helps!

**Comment by maiiDeep** [comment]
Yes, I got it. There was a newline without any string at the end of train3.txt
Thank you,
