### ISSUE TITLE
Save as .pb and single image inference

### ISSUE THREAD

**Issue by kmonachopoulos** [MarvinTeichmann/KittiSeg#113]
I am saving the model in a protobuf  format like this in the evaluate.py : 

```
tf.train.write_graph(_session.graph_def, save_dir, "FCN8_bilinear_session_Full.pb", False)
tf.train.write_graph(_session.graph_def, save_dir, "FCN8_bilinear_session_Full.pbtxt", True)
```

After that I want to do a single image inference through that .pb file using this code : 

```
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.platform import gfile
from PIL import Image

# Read the image & get statstics
img=Image.open('/path-to-image/demoImage.png')
img.show()
width, height = img.size
print(width)
print(height)

#Plot the image
#image.show()

with tf.Graph().as_default() as graph:

        with tf.Session() as sess:

                # Load the graph in graph_def
                print("load graph")

                # We load the protobuf file from the disk and parse it to retrive the unserialized graph_drf
                with gfile.FastGFile("/path-to-FCN-model/FCN8.pb",'rb') as f:

                                #Set default graph as current graph
                                graph_def = tf.GraphDef()
                                graph_def.ParseFromString(f.read())
                                #sess.graph.as_default() #new line

                                # Import a graph_def into the current default Graph
                                tf.import_graph_def(graph_def, name='')

                                # Print the name of operations in the session
                                #for op in sess.graph.get_operations():

                                    #print "Operation Name :",op.name            # Operation name
                                    #print "Tensor Stats :",str(op.values())     # Tensor name

                                # INFERENCE Here
                                l_input = graph.get_tensor_by_name('Placeholder:0')
                                l_output = graph.get_tensor_by_name('save/Assign_38:0')

                                print "l_input", l_input
                                print "l_output", l_output
                                print
                                print

                                # Acceptable feed values include Python scalars, strings, lists, numpy ndarrays, or TensorHandles.                              
                                result = sess.run(l_output, feed_dict={l_input : img}) #   <= error here
                                print(results)

                                print("Inference done")


                                # Info
                                # First Tensor name : Placeholder:0
                                # Last tensor name  : save/Assign_38:0"
```

But I get the following error in sess.run : 

```
2017-08-16 15:54:11.567779: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model
2017-08-16 15:54:11.571391: W tensorflow/core/framework/op_kernel.cc:1158] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model
Traceback (most recent call last):
  File "InferencePb2.py", line 51, in <module>
    result = sess.run(l_output, feed_dict={l_input : img}) #   <= error here
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model
	 [[Node: save/RestoreV2_38 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](save/Const, save/RestoreV2_38/tensor_names, save/RestoreV2_38/shape_and_slices)]]

Caused by op u'save/RestoreV2_38', defined at:
  File "InferencePb2.py", line 33, in <module>
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 311, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model
	 [[Node: save/RestoreV2_38 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](save/Const, save/RestoreV2_38/tensor_names, save/RestoreV2_38/shape_and_slices)]]
```

Is there any idea why I get this error? Even if I change the output tensor in order to inference in a part of the graph I still get different errors. Any suggestion is appriciated.

**Comment by kmonachopoulos** [comment]
I managed to fix the error, below is the working script to inference a single image on Fully Convolutional Networks (for whoever is interesting in an alternative segmentation algorithm from SEGNET) . This model use billinear interpolation for scaling rather than un-pooling layer. Anyway, you must set the correct input and output tensor name and pass the network from TF optimizer to set Dropout probabilities to 1. Afterwards, the inference works correctly, extracting the segmented image.

```
import tensorflow as tf # Default graph is initialized when the library is imported
import os
from tensorflow.python.platform import gfile
from PIL import Image
import numpy as np
import scipy
from scipy import misc
import matplotlib.pyplot as plt
import cv2

with tf.Graph().as_default() as graph: # Set default graph as graph

           with tf.Session() as sess:
                # Load the graph in graph_def
                print("load graph")

                # We load the protobuf file from the disk and parse it to retrive the unserialized graph_drf
                with gfile.FastGFile("/path-to-protobuf/FCN8_Freezed.pb",'rb') as f:

                                print("Load Image...")
                                # Read the image & get statstics
                                image = scipy.misc.imread('/Path-To-Image/uu_000010.png')
                                image = image.astype(float)
                                Input_image_shape=image.shape
                                height,width,channels = Input_image_shape

                                print("Plot image...")
                                #scipy.misc.imshow(image)

                                # Set FCN graph to the default graph
                                graph_def = tf.GraphDef()
                                graph_def.ParseFromString(f.read())
                                sess.graph.as_default()

                                # Import a graph_def into the current default Graph (In this case, the weights are (typically) embedded in the graph)

                                tf.import_graph_def(
                                graph_def,
                                input_map=None,
                                return_elements=None,
                                name="",
                                op_dict=None,
                                producer_op_list=None
                                )

                                # Print the name of operations in the session
                                for op in graph.get_operations():
                                        print "Operation Name :",op.name         # Operation name
                                        print "Tensor Stats :",str(op.values())     # Tensor name

                                # INFERENCE Here
                                l_input = graph.get_tensor_by_name('Inputs/fifo_queue_Dequeue:0') # Input Tensor
                                l_output = graph.get_tensor_by_name('upscore32/conv2d_transpose:0') # Output Tensor

                                print "Shape of input : ", tf.shape(l_input)
                                #initialize_all_variables
                                tf.global_variables_initializer()

                                # Run Kitty model on single image
                                Session_out = sess.run( l_output, feed_dict = {l_input : image} )

```

**Comment by shadow111** [comment]
Hello,
can you please share your  "FCN8_Freezed.pb" becuase i have   a problem where the input tensor name is not presented into my model.
Also can you please tell me how you have saved the model in evaluate.py :

Thank you

**Comment by AshutoshBachchan** [comment]
hi, I am getting this error after running my codetf.Tensor 'shuffle_batch:0' shape=(64, 256, 256, 1) dtype=float32> cannot be interpreted as a Tensor.
















import cv2
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import time
import os
import sys
from datetime import timedelta
import skimage.io as io
from queue_loader import Queue_loader
from tensorflow.python.framework.graph_util import convert_variables_to_constants
from google.protobuf import text_format
from tensorflow.python.platform import gfile

batch_size = 64
num_epochs = 1
queue_loader = Queue_loader(batch_size=batch_size, num_epochs=num_epochs)
labels = tf.one_hot(indices=queue_loader.labels, depth=15)
labels = tf.cast(labels, tf.float32)
#images = tf.cast(images, tf.float32)
images = queue_loader.images
print(images)
print(labels)
num_batches = queue_loader.num_batches

model_file = "C:\\Users\\Emage Vision\\Downloads\\checkpoints\\bv2_15.pb"

with tf.gfile.GFile(model_file, "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    #text_format.Merge(f.read(), graph_def)
with tf.Graph().as_default() as graph:

    tf.import_graph_def(graph_def, input_map=None, return_elements= None, name="", op_dict= None, producer_op_list=None)
    session = tf.Session(graph=graph)

    images_ = session.run([images])
    labels_ = session.run([labels])
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(sess=session, coord=coord)

    for op in graph.get_operations():
        print("Operation Name :", op.name)
        print("Tensor Stats :", str(op.values()))

    for i in range(2):
        print("Training Strated")
        prab_values = session.run("softmax:0", feed_dict={"input/x:0": images_, "input/y_:0": labels_, 'dropout/Placeholder:0': 0.4})
        print("result",prab_values)
'''
for op in graph.get_operations():
    print("Operation Name :", op.name)
    print("Tensor Stats :", str(op.values()))
    #images_ = session.run([images])
    #print(images_)
    #labels_ = session.run([labels])

    l_input = graph.get_tensor_by_name('input/x:0')  # Input Tensor
    l_output = graph.get_tensor_by_name('softmax:0')  # Output Tensor
    print("Shape of input : ", tf.shape(l_input))
    # initialize_all_variables

    tf.global_variables_initializer()
   # prab_values = session.run(l_output,feed_dict={l_input: images_})
    #print(prab_values)
'''

**Comment by andrewginns** [comment]
@kmonachopoulos Thanks your solution helped me understand how to do inference for my model using a .pb

**Comment by angyee** [comment]
> I managed to fix the error, below is the working script to inference a single image on Fully Convolutional Networks (for whoever is interesting in an alternative segmentation algorithm from SEGNET) . This model use billinear interpolation for scaling rather than un-pooling layer. Anyway, you must set the correct input and output tensor name and pass the network from TF optimizer to set Dropout probabilities to 1. Afterwards, the inference works correctly, extracting the segmented image.
> 
> ```
> import tensorflow as tf # Default graph is initialized when the library is imported
> import os
> from tensorflow.python.platform import gfile
> from PIL import Image
> import numpy as np
> import scipy
> from scipy import misc
> import matplotlib.pyplot as plt
> import cv2
> 
> with tf.Graph().as_default() as graph: # Set default graph as graph
> 
>            with tf.Session() as sess:
>                 # Load the graph in graph_def
>                 print("load graph")
> 
>                 # We load the protobuf file from the disk and parse it to retrive the unserialized graph_drf
>                 with gfile.FastGFile("/path-to-protobuf/FCN8_Freezed.pb",'rb') as f:
> 
>                                 print("Load Image...")
>                                 # Read the image & get statstics
>                                 image = scipy.misc.imread('/Path-To-Image/uu_000010.png')
>                                 image = image.astype(float)
>                                 Input_image_shape=image.shape
>                                 height,width,channels = Input_image_shape
> 
>                                 print("Plot image...")
>                                 #scipy.misc.imshow(image)
> 
>                                 # Set FCN graph to the default graph
>                                 graph_def = tf.GraphDef()
>                                 graph_def.ParseFromString(f.read())
>                                 sess.graph.as_default()
> 
>                                 # Import a graph_def into the current default Graph (In this case, the weights are (typically) embedded in the graph)
> 
>                                 tf.import_graph_def(
>                                 graph_def,
>                                 input_map=None,
>                                 return_elements=None,
>                                 name="",
>                                 op_dict=None,
>                                 producer_op_list=None
>                                 )
> 
>                                 # Print the name of operations in the session
>                                 for op in graph.get_operations():
>                                         print "Operation Name :",op.name         # Operation name
>                                         print "Tensor Stats :",str(op.values())     # Tensor name
> 
>                                 # INFERENCE Here
>                                 l_input = graph.get_tensor_by_name('Inputs/fifo_queue_Dequeue:0') # Input Tensor
>                                 l_output = graph.get_tensor_by_name('upscore32/conv2d_transpose:0') # Output Tensor
> 
>                                 print "Shape of input : ", tf.shape(l_input)
>                                 #initialize_all_variables
>                                 tf.global_variables_initializer()
> 
>                                 # Run Kitty model on single image
>                                 Session_out = sess.run( l_output, feed_dict = {l_input : image} )
> ```

KeyError: "The name 'Inputs/fifo_queue_Dequeue:0' refers to a Tensor which does not exist. The operation, 'Inputs/fifo_queue_Dequeue', does not exist in the graph."
@kmonachopoulos

**Comment by dungct7** [comment]
Can you explain how to transform matrix from Session_out to output image? @kmonachopoulos

**Comment by taiftahmid** [comment]
I am trying to do some inference from my own model but it seems the input and output nodes don't have any : with their name. 
My input node name: X_content
Output node name: add_37 
Due to which I get the error 
Value Error: The name 'X_content' looks like an (invalid) Operation name, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>"
Can anyone provide me with a solution to this error? 

Thanks!

**Comment by andrewginns** [comment]
@taiftahmid

Try changing your reference in code from X_content to X_content:0

You may need to reference the output of the node rather than the node itself.

**Comment by taiftahmid** [comment]
@andrewginns  
I tried your suggestion but I got the following error:

"The name 'X_content:0' refers to a Tensor which does not exist. The operation, 'X_content', does not exist in the graph."

I printed all the operations in my graph and there I did find X_content as follows

print(tf.get_default_graph().get_operations())

Output:
[<tf.Operation 'X_content' type=Placeholder>, ........

**Comment by taiftahmid** [comment]
Got the solution to the problem. 
I was using 
 `l_input = graph.get_tensor_by_name("X_content:0") # Input Tensor`
rather than 
`l_input = tf.get_default_graph().get_tensor_by_name("X_content:0") # Input Tensor`

**Comment by kmonachopoulos** [comment]
> > I managed to fix the error, below is the working script to inference a single image on Fully Convolutional Networks (for whoever is interesting in an alternative segmentation algorithm from SEGNET) . This model use billinear interpolation for scaling rather than un-pooling layer. Anyway, you must set the correct input and output tensor name and pass the network from TF optimizer to set Dropout probabilities to 1. Afterwards, the inference works correctly, extracting the segmented image.
> > ```
> > import tensorflow as tf # Default graph is initialized when the library is imported
> > import os
> > from tensorflow.python.platform import gfile
> > from PIL import Image
> > import numpy as np
> > import scipy
> > from scipy import misc
> > import matplotlib.pyplot as plt
> > import cv2
> > 
> > with tf.Graph().as_default() as graph: # Set default graph as graph
> > 
> >            with tf.Session() as sess:
> >                 # Load the graph in graph_def
> >                 print("load graph")
> > 
> >                 # We load the protobuf file from the disk and parse it to retrive the unserialized graph_drf
> >                 with gfile.FastGFile("/path-to-protobuf/FCN8_Freezed.pb",'rb') as f:
> > 
> >                                 print("Load Image...")
> >                                 # Read the image & get statstics
> >                                 image = scipy.misc.imread('/Path-To-Image/uu_000010.png')
> >                                 image = image.astype(float)
> >                                 Input_image_shape=image.shape
> >                                 height,width,channels = Input_image_shape
> > 
> >                                 print("Plot image...")
> >                                 #scipy.misc.imshow(image)
> > 
> >                                 # Set FCN graph to the default graph
> >                                 graph_def = tf.GraphDef()
> >                                 graph_def.ParseFromString(f.read())
> >                                 sess.graph.as_default()
> > 
> >                                 # Import a graph_def into the current default Graph (In this case, the weights are (typically) embedded in the graph)
> > 
> >                                 tf.import_graph_def(
> >                                 graph_def,
> >                                 input_map=None,
> >                                 return_elements=None,
> >                                 name="",
> >                                 op_dict=None,
> >                                 producer_op_list=None
> >                                 )
> > 
> >                                 # Print the name of operations in the session
> >                                 for op in graph.get_operations():
> >                                         print "Operation Name :",op.name         # Operation name
> >                                         print "Tensor Stats :",str(op.values())     # Tensor name
> > 
> >                                 # INFERENCE Here
> >                                 l_input = graph.get_tensor_by_name('Inputs/fifo_queue_Dequeue:0') # Input Tensor
> >                                 l_output = graph.get_tensor_by_name('upscore32/conv2d_transpose:0') # Output Tensor
> > 
> >                                 print "Shape of input : ", tf.shape(l_input)
> >                                 #initialize_all_variables
> >                                 tf.global_variables_initializer()
> > 
> >                                 # Run Kitty model on single image
> >                                 Session_out = sess.run( l_output, feed_dict = {l_input : image} )
> > ```
> 
> KeyError: "The name 'Inputs/fifo_queue_Dequeue:0' refers to a Tensor which does not exist. The operation, 'Inputs/fifo_queue_Dequeue', does not exist in the graph."
> @kmonachopoulos

What are the input / output tensor names of your model?

**Comment by kmonachopoulos** [comment]
> Can you explain how to transform matrix from Session_out to output image? @kmonachopoulos

```
Session_out_reshaped = tf.reshape(Session_out, [375, 1242, 2])

# Slice the output to two different matrices
Prob_1_Tensor = tf.slice(Session_out_reshaped, [0, 0, 0], [375, 1242, 1])
Prob_2_Tensor = tf.slice(Session_out_reshaped, [0, 0, 1], [375, 1242, 1])

Prob_1_Tensor_Normalized = Prob_1_Tensor.eval() * 255.0
Prob_2_Tensor_Normalized = Prob_2_Tensor.eval() * 255.0
```

I hope that helps .

**Comment by NilakshanKunananthaseelan** [comment]
> I managed to fix the error, below is the working script to inference a single image on Fully Convolutional Networks (for whoever is interesting in an alternative segmentation algorithm from SEGNET) . This model use billinear interpolation for scaling rather than un-pooling layer. Anyway, you must set the correct input and output tensor name and pass the network from TF optimizer to set Dropout probabilities to 1. Afterwards, the inference works correctly, extracting the segmented image.
> 
> ```
> import tensorflow as tf # Default graph is initialized when the library is imported
> import os
> from tensorflow.python.platform import gfile
> from PIL import Image
> import numpy as np
> import scipy
> from scipy import misc
> import matplotlib.pyplot as plt
> import cv2
> 
> with tf.Graph().as_default() as graph: # Set default graph as graph
> 
>            with tf.Session() as sess:
>                 # Load the graph in graph_def
>                 print("load graph")
> 
>                 # We load the protobuf file from the disk and parse it to retrive the unserialized graph_drf
>                 with gfile.FastGFile("/path-to-protobuf/FCN8_Freezed.pb",'rb') as f:
> 
>                                 print("Load Image...")
>                                 # Read the image & get statstics
>                                 image = scipy.misc.imread('/Path-To-Image/uu_000010.png')
>                                 image = image.astype(float)
>                                 Input_image_shape=image.shape
>                                 height,width,channels = Input_image_shape
> 
>                                 print("Plot image...")
>                                 #scipy.misc.imshow(image)
> 
>                                 # Set FCN graph to the default graph
>                                 graph_def = tf.GraphDef()
>                                 graph_def.ParseFromString(f.read())
>                                 sess.graph.as_default()
> 
>                                 # Import a graph_def into the current default Graph (In this case, the weights are (typically) embedded in the graph)
> 
>                                 tf.import_graph_def(
>                                 graph_def,
>                                 input_map=None,
>                                 return_elements=None,
>                                 name="",
>                                 op_dict=None,
>                                 producer_op_list=None
>                                 )
> 
>                                 # Print the name of operations in the session
>                                 for op in graph.get_operations():
>                                         print "Operation Name :",op.name         # Operation name
>                                         print "Tensor Stats :",str(op.values())     # Tensor name
> 
>                                 # INFERENCE Here
>                                 l_input = graph.get_tensor_by_name('Inputs/fifo_queue_Dequeue:0') # Input Tensor
>                                 l_output = graph.get_tensor_by_name('upscore32/conv2d_transpose:0') # Output Tensor
> 
>                                 print "Shape of input : ", tf.shape(l_input)
>                                 #initialize_all_variables
>                                 tf.global_variables_initializer()
> 
>                                 # Run Kitty model on single image
>                                 Session_out = sess.run( l_output, feed_dict = {l_input : image} )
> ```
The Session_out gives the weights of each layer,not the activations.
How to get the activations from .pb inference?

**Comment by NilakshanKunananthaseelan** [comment]
I got the results with a minor change 
l_input = graph.get_operations()[0].name+':0'
l_output = graph.get_operations()[5].name+':0'


 where each index in l_output points a layer in the model
