### ISSUE TITLE
Is loading vgg16 model redundant in demo.py?

### ISSUE THREAD

**Issue by mrfortynine** [MarvinTeichmann/KittiSeg#13]
Marvin,

Just to make sure I understand how KittiSeg works correctly. When I run demo.py, the code load vgg16 model. But these parameters would eventually be overwritten by the fine tuned weights in the checkpoint. Is my understanding correct?

Thanks
Jia

**Comment by MarvinTeichmann** [comment]
Hi Jia,

yes, you are absolutely right. Havn't found the time yet to implement a need solution. Feel free to add a patch, if you can think of an easy way to avoid this ;).

Marvin
