### ISSUE TITLE
any suggestion on how to train in batch?

### ISSUE THREAD

**Issue by ZhengHe-MD** [MarvinTeichmann/KittiSeg#16]
Thank you for open sourcing this project and your tensorvision backend. It helps a lot.

I can see that when you generate image and label, in training phase, you call jitter_input on both the input image and the label.

But if we want to train in batch, we have to ensure that all input images have the same shape. Here are my questions.

1. I've seen your code that resizes both image and label, but I don't understand what should the label be when you make the input image larger or smaller. Any best practice on this?

2. I can image that an approach I can take is to pad all the images to the same shapes, and assign the padded pixels void label. and ignore any predictions on the padding pixels later. what do you think of this approach?

3. another question is that, if you do random crop and resize to input image and label, the model you trained is fed with only part of the image and label, how do you make it predict the whole image on test set?

thx！

**Comment by MarvinTeichmann** [comment]
Most of your questions seems to be already answered in code:

>  1. I've seen your code that resizes both image and label, but I don't understand what should the label be when you make the input image larger or smaller. Any best practice on this?

'resize_label_image' and 'random_resize' implements this. So just use that.

>  2. I can image that an approach I can take is to pad all the images to the same shapes, and assign the padded pixels void label. and ignore any predictions on the padding pixels later. what do you think of this approach?

This is implemented by `resize_label_image_with_pad`, so you can use that.

> 3. another question is that, if you do random crop and resize to input image and label, the model you trained is fed with only part of the image and label, how do you make it predict the whole image on test set?

This is not a problem. I train with cropping, evaluate without. See `demo.py`.

**Comment by MarvinTeichmann** [comment]
Regarding your initial question. If you want to train in batches you need to make sure, that each image in an batch is has same size. Use `resize_label_image_with_pad` or implement a deterministic function like `random_crop` which always outputs the same shape or simply use `resize_label_image` to resize all image to the same shape.

Alternativly you can continue using `random_crop` and `random_resize` but make sure, that you always output `batch_size` many images with the same shape.

**Comment by surfreta** [comment]
Hi Marvin,

Generally, if the data set is of different size, what kind of modifications on the code that I have to make to handle this scenario.  For the most extreme case, if batch_size is setup as 1, do I still to make any modifications? Thank you for the clarification.

**Comment by xxxy-931231** [comment]
@ZhengHe-MD
你好 我尝试把batch_size改成32，但是训练会报错，改成8就可以训练，这是我内存不够大的原因吗，16G内存，还有我想问下我把batch_size改成8训练速度下降了，这是为什么？我理解训练速度应该变快
