### ISSUE TITLE
Import module 'seg_utils' Error

### ISSUE THREAD

**Issue by colorfulCloud** [MarvinTeichmann/KittiSeg#17]
I followed the instructions, and downloaded vgg16.npy and data_road.zip successfully, but when I run the command:  python demo.py --input_image data/demo/demo.png --output_image data/demo/demo_seg.png 
I got the error message as following: 
Traceback (most recent call last):
  File "demo.py", line 51, in <module>
    from seg_utils import seg_utils as seg
ImportError: No module named 'seg_utils'
I use Anaconda3 (64-bit)/Windows 7

**Comment by MarvinTeichmann** [comment]
Seg_utils is a linux symlink defined [here](https://github.com/MarvinTeichmann/KittiSeg/blob/master/incl/seg_utils). Make sure, that anaconda finds the folder [incl](https://github.com/MarvinTeichmann/KittiSeg/blob/master/incl) and is able to import all its subfolders referenced by the symlinks there.

The code runs under linux out of the box. I have not tested the code using windows. So you might run into more errors.  Most deep learning code is our there is written and tested under linux. So if you are planning to do some deep learning, I would strongly recommend learning to use linux. It is nor that hard!

Btw. Even my colleagues at Microsoft are using Linux for there deep learning infrastructure. So I recommend following the choices of the market leader when it comes to operating systems ;).

**Comment by jiao0805** [comment]
Have you solved this problem under Win7?
I use python 3.5 and tensorflow 1.0 gpu version under win7.

**Comment by baidut** [comment]
For windows user, save the following code as `install_windows.bat` and put it in your `KittiSeg` folder, then run it as admin.
Also please make sure you initialized all your submodules with `git submodule update --init --recursive`

```
del %~dp0\incl\evaluation
del %~dp0\incl\seg_utils
del %~dp0\incl\tensorflow_fcn
del %~dp0\incl\tensorvision
mklink /D %~dp0\incl\evaluation %~dp0\submodules\evaluation
mklink /D %~dp0\incl\seg_utils %~dp0\submodules\evaluation\kitti_devkit
mklink /D %~dp0\incl\tensorflow_fcn %~dp0\submodules\tensorflow-fcn
mklink /D %~dp0\incl\tensorvision %~dp0\submodules\TensorVision\tensorvision
echo ok
pause
```
![image](https://cloud.githubusercontent.com/assets/6234266/23882311/b686b6d0-089a-11e7-9f9d-9f959151a4e6.png)

It will create the symbolic links for you, as follows

![image](https://cloud.githubusercontent.com/assets/6234266/23882342/d85b32ea-089a-11e7-9592-6a20e3be8b79.png)

**Comment by MarvinTeichmann** [comment]
Let me know, whether the rest of the code works fine under Windows.

**Comment by baidut** [comment]
Demo works fine under **Window 10 TensorFlow 1.0 cuda8.0 cudnn v5.1 python3.5**
`python demo.py --input_image data/demo/demo.png`

I will report the issue when encountered.

**Comment by jhtao1860** [comment]
to baidut，大牛！

**Comment by jhtao1860** [comment]
two main issues(1:'seg_utils' Error ;2:'RUNS/KittiSeg_pretrained.zip'  ) I met are solved.
Thanks!

The demo works fine under
 Window 10
 TensorFlow 1.0
 only CPU
 python3.5(this version can install TensorFlow 1.0 very easy )
python demo.py --input_image data/demo/demo.png

**Comment by MahmoudYounes** [comment]
I am using debian 8 and I have the same problem. I run using the terminal: 
python demo.py --input_image data/demo/demo.png

is there anything more I should do ?

**Comment by MarvinTeichmann** [comment]
Seg_utils is a linux symlink defined [here](https://github.com/MarvinTeichmann/KittiSeg/blob/master/incl/seg_utils). Make sure, that your system finds the symlink and that python includes it as path of its path.

**Comment by shivam-kotwalia** [comment]
(Reporting Issue ) It is not even working on Ubuntu 16, python 2.7, and Tensorflow 1.0

**Comment by shivam-kotwalia** [comment]
For those who are stilling figuring out this, please append the kitti_devkit path to your python path 
```
import sys
sys,path.append("/home/shivam/Desktop/work/project/KittiSeg/submodules/evaluation/kitti_devkit")
```

Or just symlink kitti_dev in your Python Directory 
ln -s /home/shivam/Desktop/work/project/KittiSeg/submodules/evaluation/kitti_devkit /home/shivam/Desktop/work/venvs/TensorVision/lib/python2.7/

**Comment by zishanahmed08** [comment]
Doesnt work on my configuration - python 3.5 , tensorflow 1.0 cpu only, win7.
Already tried the install_windows.bat file by baidut.

**Comment by xiangweirs** [comment]
Dear @baidut @MarvinTeichmann @jhtao1860 
When I run demo.py, it doesn't work and display error information as blow:
**2017-07-08 12:14:53,252 INFO No environment variable 'TV_PLUGIN_DIR' found. Set to 'C:\Users\dell/tv-plugins'.
2017-07-08 12:14:53,252 INFO No environment variable 'TV_STEP_SHOW' found. Set to '50'.
2017-07-08 12:14:53,252 INFO No environment variable 'TV_STEP_EVAL' found. Set to '250'.
2017-07-08 12:14:53,252 INFO No environment variable 'TV_STEP_WRITE' found. Set to '1000'.
2017-07-08 12:14:53,252 INFO No environment variable 'TV_MAX_KEEP' found. Set to '10'.
2017-07-08 12:14:53,252 INFO No environment variable 'TV_STEP_STR' found. Set to 'Step {step}/{total_steps}: loss = {loss_value:.2f}; lr = {lr_value:.2e}; {sec_per_batch:.3f} sec (per Batch); {examples_per_sec:.1f} imgs/sec'.
Traceback (most recent call last):
ArgumentError: argument --gpus: conflicting option string: --gpus**
what Should do to work it out?
Thanks very much!

**Comment by zhaojingji** [comment]
@jiao0805 Have you solved this problem（ImportError: No module named 'seg_utils'）, ask for help, thank you，The solution baidut provides, I have tried it，but no work。

**Comment by louxy126** [comment]
Hi,@xiangweirs 
i meet the same problem with you,did you fixed it?

**Comment by Timmmmmms** [comment]
> For windows user, save the following code as `install_windows.bat` and put it in your `KittiSeg` folder, then run it as admin.
> Also please make sure you initialized all your submodules with `git submodule update --init --recursive`
> 
> ```
> del %~dp0\incl\evaluation
> del %~dp0\incl\seg_utils
> del %~dp0\incl\tensorflow_fcn
> del %~dp0\incl\tensorvision
> mklink /D %~dp0\incl\evaluation %~dp0\submodules\evaluation
> mklink /D %~dp0\incl\seg_utils %~dp0\submodules\evaluation\kitti_devkit
> mklink /D %~dp0\incl\tensorflow_fcn %~dp0\submodules\tensorflow-fcn
> mklink /D %~dp0\incl\tensorvision %~dp0\submodules\TensorVision\tensorvision
> echo ok
> pause
> ```
> ![image](https://cloud.githubusercontent.com/assets/6234266/23882311/b686b6d0-089a-11e7-9f9d-9f959151a4e6.png)
> 
> It will create the symbolic links for you, as follows
> 
> ![image](https://cloud.githubusercontent.com/assets/6234266/23882342/d85b32ea-089a-11e7-9592-6a20e3be8b79.png)

cannot do this

![image](https://user-images.githubusercontent.com/39646606/49373227-34bf9480-f738-11e8-95d5-98855c76b17c.png)

**Comment by baidut** [comment]
> cannot do this

Please run it as admin @Timmmmmms
