### ISSUE TITLE
Cannot get KittiSeg_pretrained.zip

### ISSUE THREAD

**Issue by zhixy** [MarvinTeichmann/KittiSeg#18]
As the titile, I cannot get the file, I don't what is the problem, maybe the network problem. Can you please send this file to me? Thanks in advance! My e-mail: zhixy@shanghaitech.edu.cn

**Comment by MarvinTeichmann** [comment]
The file is way to large to be send by email. Have you tried download the file directly form: [ftp://mi.eng.cam.ac.uk/pub/mttt2/models/KittiSeg_pretrained.zip](ftp://mi.eng.cam.ac.uk/pub/mttt2/models/KittiSeg_pretrained.zip)?

**Comment by MarvinTeichmann** [comment]
@zhixy You might also have been affected by

**Comment by zhixy** [comment]
Yes, I have downloaded successfully, thank you very much!

**Comment by xiaomofang** [comment]
> 
I cannot get the file too. Can you please send this file to me? Thanks in advance! My e-mail: [zhixy@shanghaitech.edu.cn](mailto:lmf37pq@163.com)
