### ISSUE TITLE
run demo.py

### ISSUE THREAD

**Issue by overfitover** [MarvinTeichmann/KittiSeg#182]
I have the result, when I run the demo.py.
![demo2_green](https://user-images.githubusercontent.com/38489551/43185227-d9b77d18-901d-11e8-9ca0-d81f58797830.png)

any suggestion?

**Comment by HelloZEX** [comment]
Maybe the “KittiSeg_pretrained” is wrong

**Comment by overfitover** [comment]
maybe.Thanks for your reply.

**Comment by Gatsby23** [comment]
> I have the result, when I run the demo.py. ![demo2_green](https://user-images.githubusercontent.com/38489551/43185227-d9b77d18-901d-11e8-9ca0-d81f58797830.png)
> 
> any suggestion?

Where have you download the pretrained model ?
