### ISSUE TITLE
VGG16.npy file not found error. Not utf encoded. Please Help!!! It's making me go crazy!

### ISSUE THREAD

**Issue by KavyaRavulapati** [MarvinTeichmann/KittiSeg#184]
Hello, I'm trying to train the model with kitti data. I'm getting an error as below:

ERROR File '/Users/kavyaravulapati/KittiSeg/hypes/../DATA/weights/vgg16.npy' not found. Download it from ftp://mi.eng.cam.ac.uk/pub/mttt2/models/vgg16.npy

I tried downloading it from the above link using the command below:
wget ftp://mi.eng.cam.ac.uk/pub/mttt2/models/vgg16.npy

After the download, I got this message:
‘vgg16.npy’ saved [553431761]

But once I open the data folder and open the vgg16.npy file, it says:
Error! vgg16.npy is not utf-8 encoded
Saving disabled 
See console for more details

I tried using ftp://mi.eng.cam.ac.uk/pub/mttt2/models/vgg16.npy as url in my browser, and downloaded it. But my Mac says that it cannot open the file.

I'm clueless now on what to do. Please help me solve this problem. I've gone through the other issues regaring this, but nothing helped. :( @MarvinTeichmann sir please help!

**Comment by yanchunhui** [comment]
hi，maybe you should put the vgg16.npy in the path as `KittiSeg/data/weights/vgg16.npy.`
as for downloading the file,you can try some other download tools, such as FDM

**Comment by KavyaRavulapati** [comment]
Thanks a lot @yanchunhui, I figured it out. This is what I did:

First rename data to DATA, and then create a new folder named 'weights' inside data. The vgg16.npy file should be present in two places: one inside data, and the other inside /data/weights. 

Hope this helps!
