### ISSUE TITLE
No such file or directory: 'RUNS/KittiSeg_pretrained.zip'

### ISSUE THREAD

**Issue by bubalazi** [MarvinTeichmann/KittiSeg#19]
Hi,

After downloading the data, installing the requirements.txt packages and tensorflow I attempted the demo and got this error.

python demo.py --input_image data/demo/demo.png 
2017-03-10 07:50:36,788 INFO No environment variable 'TV_PLUGIN_DIR' found. Set to '/home/lap/tv-plugins'.
2017-03-10 07:50:36,788 INFO No environment variable 'TV_STEP_SHOW' found. Set to '50'.
2017-03-10 07:50:36,788 INFO No environment variable 'TV_STEP_EVAL' found. Set to '250'.
2017-03-10 07:50:36,788 INFO No environment variable 'TV_STEP_WRITE' found. Set to '1000'.
2017-03-10 07:50:36,788 INFO No environment variable 'TV_MAX_KEEP' found. Set to '10'.
2017-03-10 07:50:36,788 INFO No environment variable 'TV_STEP_STR' found. Set to 'Step {step}/{total_steps}: loss = {loss_value:.2f}; lr = {lr_value:.2e}; {sec_per_batch:.3f} sec (per Batch); {examples_per_sec:.1f} imgs/sec'.
2017-03-10 07:50:36,788 INFO Download URL: ftp://mi.eng.cam.ac.uk/pub/mttt2/models/KittiSeg_pretrained.zip
2017-03-10 07:50:36,789 INFO Download DIR: RUNS
Traceback (most recent call last):
  File "demo.py", line 216, in <module>
    tf.app.run()
  File "/media/lap/data/.virtualenvs/KittySeg/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "demo.py", line 124, in main
    maybe_download_and_extract(runs_dir)
  File "demo.py", line 87, in maybe_download_and_extract
    download_name = tv_utils.download(weights_url, runs_dir)
  File "incl/tensorvision/utils.py", line 48, in download
    reporthook=_progress)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 249, in retrieve
    tfp = open(filename, 'wb')
IOError: [Errno 2] No such file or directory: 'RUNS/KittiSeg_pretrained.zip'

Did I miss a step?

**Comment by MarvinTeichmann** [comment]
No, this is strange. The script should download the file `ftp://mi.eng.cam.ac.uk/pub/mttt2/models/KittiSeg_pretrained.zip` to dir `RUNS`. Did the download complete? Maybe try manually download that file.

**Comment by bubalazi** [comment]
Firts attempt log:

(KittySeg) lap@home:/media/lap/data/projects/KittiSeg (master)*$ wget ftp://mi.eng.cam.ac.uk/pub/mttt2/models/KittiSeg_pretrained.zip
--2017-03-10 13:48:01--  ftp://mi.eng.cam.ac.uk/pub/mttt2/models/KittiSeg_pretrained.zip
           => ‘KittiSeg_pretrained.zip’
Resolving mi.eng.cam.ac.uk (mi.eng.cam.ac.uk)... 129.169.82.147
Connecting to mi.eng.cam.ac.uk (mi.eng.cam.ac.uk)|129.169.82.147|:21... connected.
Logging in as anonymous ... 
Log-in incorrect.

After couple of minutes when I retried it went well. Perhaps the authorization requirement was lifted meanwhile.

**Comment by bubalazi** [comment]
The FTP server is randomly allowing the download to happen.

**Comment by MarvinTeichmann** [comment]
I will look into this. Although the ftp server is not under my control. So I there might not be to much I can do. :pensive:

**Comment by MarvinTeichmann** [comment]
Ok, the issue was, that the server did only allow up to 64 for anonymous connections at the same time. The limit is now increased to 256 and we hope that this is enough for now.

The repository recently went viral, this has increased the overall download request quite a bit ;).

**Comment by bubalazi** [comment]
Maybe we should collectively share the data to ease up load on the server. Is a torrent a legal option?

**Comment by MarvinTeichmann** [comment]
Legally I don't see any problems using a torrent. I see however two practical issues. Firstly my department blocks any UDP and torrent traffic. So I won't really be able to seed.

Secondly, I much prefer a simple setup pipeline. Currently the user only needs to run one script and the data files are automatically loaded and copied into the right dir. This has the charm, that no much can go wrong.

So let's hope that the increase to 256 connections is more enough for now ;). I have been trying to download a couple of times within the last hours and had no problems.

**Comment by bubalazi** [comment]
Yes, thanks, it is working now.

**Comment by louisquinn** [comment]
Hi @MarvinTeichmann, 

It seems like the download limit for KittiBox_pretrained.zip has been reached again!
Are you able to increase the download limit?

**Comment by MarvinTeichmann** [comment]
Thanks for informing me.  The connection limit is reset automatically once per hour. So if you try again in a few minutes it should work.

**Comment by gizmowiki** [comment]
Hi @MarvinTeichmann 

I guess the error is due to not having RUNS directory in the project as when I created the directory and run again, the script has started to download the file.

**Comment by iliTheFallen** [comment]
Thanks gizmowiki! Yeah it is correct!

**Comment by dbuscombe-usgs** [comment]
Tried several times to download the KittiSeg_pretrained file in the past couple of days, from command line and through ftp. Really, really slow download, and it failed every time. Could somebody put the file up on a faster server or dropbox or something? I would really like to run the demo and give this a try. Thanks

**Comment by chauhan-utk** [comment]
I downloaded the file and put it in RUNS directory. It is still not working and when I try to run demo.py again then it tries to download again. What should I do?

**Comment by zishanahmed08** [comment]
I have been constantly trying to download but without success .Could someone provide it me?@chauhan-uk?

**Comment by chauhan-utk** [comment]
@zishanahmed08 I used the link given in console to download via IDM. Decent download speed.
Here is the link: ftp://129.169.82.147/pub/mttt2/models/KittiSeg_pretrained.zip

**Comment by zishanahmed08** [comment]
@chauhan-uk I am unable to download from the link even after repeated attempts.Coul you please share your local copy.My mail id is zishanahmed.08@gmail.com

**Comment by gizmowiki** [comment]
If the owner has no problem I have stored the file in Dropbox. You can access it from [here](https://www.dropbox.com/s/eygjnz1k5sb2l35/KittiSeg_pretrained.zip?dl=0)

**Comment by kreid415** [comment]
I was having the same error. I manually created a RUNS directory and then reran the command "python demo.py --input_image data/demo/demo.png" and it began the KittiSeg_pretrained.zip download automatically.

**Comment by HXKwindwizard** [comment]
@kreid415 I used yours method. It works. Thank you

**Comment by SpearBorge** [comment]
@chauhan-utk I used your method. It works. Thank you!

**Comment by saviogeorge** [comment]
@kreid415 I also used the same method and it works Thank You!

**Comment by igormahall** [comment]
> If the owner has no problem I have stored the file in Dropbox. You can access it from [here](https://www.dropbox.com/s/eygjnz1k5sb2l35/KittiSeg_pretrained.zip?dl=0)

Hello friend. Would you mind to send me the file? 
I simply can not download it. Thank you.
