### ISSUE TITLE
git clone command error

### ISSUE THREAD

**Issue by amiltonwong** [MarvinTeichmann/KittiSeg#2]
Hi, @MarvinTeichmann ,

I try the command as listed in README.md, 

$ git clone git@github.com:MarvinTeichmann/KittiSeg.git

I got the following error:
```
Cloning into 'KittiSeg'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Any suggestion to fix this problem? THX~

**Comment by MarvinTeichmann** [comment]
Hi,

I suspect this is a github issue. Have you added any public key to your

**Comment by MarvinTeichmann** [comment]
Hi,
I suspect this is due to a wrong ssh configuration. A possible solution is discussed at  [Stackoverflow](http://stackoverflow.com/questions/11585636/ssh-clone-not-working-with-github).

As  quick fix you can also clone the repository using https: `https://github.com/MarvinTeichmann/KittiSeg.git`.

**Comment by amiltonwong** [comment]
Hi, @MarvinTeichmann ,

Thanks for your reply. I work it out temporarily by 
```
git clone https://github.com/MarvinTeichmann/KittiSeg.git
```

However, when update the submodules, the ssh key issue still exists:
```
root@milton-OptiPlex-9010:/data/code/KittiSeg# git submodule update --init --recursive
Cloning into 'submodules/TensorVision'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:TensorVision/TensorVision.git' into submodule path 'submodules/TensorVision' failed
root@milton-OptiPlex-9010:/data/code/KittiSeg#
```

I may have a look on this [Stackoverflow](http://stackoverflow.com/questions/11585636/ssh-clone-not-working-with-github) first

**Comment by MarvinTeichmann** [comment]
Yes, I have not thought of the submodules. You could of course change the url of both submodules to the `https` Version. Instructions for this can be found [here](https://jtrancas.wordpress.com/2011/02/06/git-submodule-location/). On the other hand, setting up your github ssh correctly will be the better way ;).

**Comment by amiltonwong** [comment]
Thanks @MarvinTeichmann , I did it by setting up the public key for ssh to github from [Stackoverflow](https://help.github.com/articles/connecting-to-github-with-ssh/).
Both commands (git clone and git submodule) do work now.
