### ISSUE TITLE
Out of Memory on 2GB GPU

### ISSUE THREAD

**Issue by bubalazi** [MarvinTeichmann/KittiSeg#20]
Hello,

I attempted to run the training example and ran into an OOM condition. Please find below a detailed log. 

**Could you provide advice as to how the training data can be fed in smaller batches?**

LOG:
...
      `I tensorflow/core/common_runtime/bfc_allocator.cc:696] 20 Chunks of size 256 totalling 5.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 5 Chunks of size 512 totalling 2.5KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 7 Chunks of size 1024 totalling 7.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1280 totalling 1.2KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 14 Chunks of size 2048 totalling 28.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 3 Chunks of size 4096 totalling 12.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 3 Chunks of size 6912 totalling 20.2KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 3 Chunks of size 16384 totalling 48.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 32768 totalling 32.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 3 Chunks of size 147456 totalling 432.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 3 Chunks of size 294912 totalling 864.0KiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 3 Chunks of size 589824 totalling 1.69MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 3 Chunks of size 1179648 totalling 3.38MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 5 Chunks of size 2359296 totalling 11.25MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 3 Chunks of size 4718592 totalling 13.50MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 11 Chunks of size 9437184 totalling 99.00MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 67108864 totalling 128.00MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 411041792 totalling 784.00MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 480399360 totalling 458.14MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 1.46GiB
I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                  1573257216
InUse:                  1573257216
MaxInUse:               1573257216
NumAllocs:                      93
MaxAllocSize:            480399360

W tensorflow/core/common_runtime/bfc_allocator.cc:274] ************************************************************************************************xxxx
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 16.0KiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[4096]
^C^Z
[1]+  Stopped                 python train.py --hypes hypes/KittiSeg.json`

**Comment by MarvinTeichmann** [comment]
Well, the batch size is already 1. But you can lower the resolution. For a start set `resize_image=True` in [https://github.com/MarvinTeichmann/KittiSeg/blob/master/hypes/KittiSeg.json](KittiSeg.json) and play around with "image_height" : 384, "image_width" : 1248. The package will automatically resize the image and label to the provided resolution, using bilinear interpolation.

If you are willing to invest slightly more time, you can perform random cropping. Crop 256 X 256 regions in original resolution from the image. The model is fully convolutional, so you can train on those crops and perform inference on the full image without any distortions.

**Comment by bubalazi** [comment]
Thanks a lot. Will give it a try.

**Comment by lrthorita** [comment]
Hi @MarvinTeichmann.
I'm having the same problem about OOM. I have already tried to lower the resolution and perform random cropping, but I still get this error message:
`ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape [7,7,512,4096] [[Node: fc6/biases/Adam_2/Assign = Assign[T=DT_FLOAT, _class=["loc:@fc6/weights"], use_locking=true, validate_shape=true, _device="/job:localhost;replica:0/task:0/gpu:0"](fc6/weights/Adam_2, fc6/weights/Adam_2/Initializer/Const)]]`

Looks like it is not about the memory occupied by data, but about the memory occupied by weights tensors.

**Comment by MarvinTeichmann** [comment]
Deep learning is highly memory intensive. The computational results of all layers needs to be stored to compute the gradients. Reducing the input size will also reduce the size of intermediate results, so this should be the way to go. Alternativly you can modify the architecture to use less layers. (Maybe VGG with 8 Layers)? However 2GB is not much, you will not get the same results as with 11GB.
