### ISSUE TITLE
Attribute error module scipy.misc has no attribute imread

### ISSUE THREAD

**Issue by cyrineee** [MarvinTeichmann/KittiSeg#201]

**Comment by MarvinTeichmann** [comment]
It was removed in the newest scipy version. Use an older one:
https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.misc.imread.html

**Comment by cyrineee** [comment]
@MarvinTeichmann  I changed with imread from mayplotlib.pyplot and it works .now i have a problem with 'toimage' attribute of scipy.misc . How can i fix it ?
