### ISSUE TITLE
Error when import module 'seg_utils'

### ISSUE THREAD

**Issue by jiao0805** [MarvinTeichmann/KittiSeg#21]
When I run demo.py use : 
  python demo.py --input_image data/demo/demo.png

There is an ImportError : 
cannot import name 'seg_utils'

How can I solve it?

**Comment by chsahit** [comment]
Make sure you initialized all your submodules with `git submodule update --init --recursive`

**Comment by MarvinTeichmann** [comment]
In addition, `seg_utils` is a symlink defined in [incl](https://github.com/MarvinTeichmann/KittiSeg/tree/master/incl). Make sure that your system finds that.

Also see issue #17 if you are using windows.

**Comment by MarvinTeichmann** [comment]
Closed as duplicate. Please refer to #17 for more questions.
