### ISSUE TITLE
Failed to interpret vgg16.npy as pickle

### ISSUE THREAD

**Issue by jedavis82** [MarvinTeichmann/KittiSeg#22]
[vgg16.txt](https://github.com/MarvinTeichmann/KittiSeg/files/840157/vgg16.txt)
Hi Marvin, 

Thank you for your efforts in coding all of this up.  I was trying to run your demo and am able to download the data_road.zip and extract it successfully using your download_data.py script.  However, when I try to run the demo using the demo.py script, I get an error saying that the script failed to interpret "DATA/vgg16.npy" as a pickle.  Upon inspection of vgg16.npy, it appears to be downloaded as a dropbox error HTML file.  I have attached vgg16.txt since I couldn't attach the .npy file type, but its contents are what is contained in vgg16.npy whenever I download it.  I didn't know if you were aware of this error or know of a way to resolve it.  Thanks for the help and code!

**Comment by MarvinTeichmann** [comment]
I have reuploaded the File to our FTP server. You can now find it here:

ftp://mi.eng.cam.ac.uk/pub/mttt2/models/vgg16.npy

**Comment by anonym24** [comment]
where to put it?

**Comment by anonym24** [comment]
omg, I had to rename data to DATA

**Comment by anonym24** [comment]
issue with lowercase, uppercase, pls fix it
