### ISSUE TITLE
Issue on mlticlass segmentation

### ISSUE THREAD

**Issue by bendidi** [MarvinTeichmann/KittiSeg#29]
Hello , 
thanks for sharing this amazing work 
I'm trying to implement for 5 colors ( black for background , blue , red, green, white ) , I changed the json file in hypes , changed the functions in the input script to load the images and ground truths as you've specified in the doc.
The images got loaded successfully , the problem I got was in calculating the loss of training ('kitti_multiloss.py')  if I understood correctly , there was a shape mismatch somewhere , even through I resized my images to the same shape of yours , calculating the loss need changing for multi class seg. ?

thanks again for you work

**Comment by MarvinTeichmann** [comment]
Are you trying to perform non-binary segmentation? Please have a look into the discussion in issue #15. 

The loss is fine to segment multiple classes. You need however to adapt the input producer and evaluation code.

**Comment by MarvinTeichmann** [comment]
I just had a look at the loss implementation. "Num classes" is hard coded in there. You need to change the 2 in line [65](https://github.com/MarvinTeichmann/KittiSeg/blob/master/decoder/kitti_multiloss.py#L65), [66](https://github.com/MarvinTeichmann/KittiSeg/blob/master/decoder/kitti_multiloss.py#L66) and [69](https://github.com/MarvinTeichmann/KittiSeg/blob/master/decoder/kitti_multiloss.py#L69) to "num_classes".

**Comment by gudmundurme** [comment]
If you get this to work let me know, I'm also about to implement this

**Comment by MarvinTeichmann** [comment]
Let's move all discussions for this to one place. Please add further comments to #15.

**Comment by bendidi** [comment]
Thanks @MarvinTeichmann 
I've changed the input file , and I'm quite confident I got it right , I still haven't changed the evaluation file through ...
@gudmundurme I'll keep you updated on issue #15.
sorry for the hassle
