### ISSUE TITLE
I can't download KittiSeg_pretrained.zip ...

### ISSUE THREAD

**Issue by heyulinxp** [MarvinTeichmann/KittiSeg#33]
I just can't download this file!!!!!!!!!!!!!!!!!!!
I just don't know why this ftp is so poor
Who can share this file? Please~

**Comment by 1120651074** [comment]
I can't download yet,so sad!!!!

**Comment by MarvinTeichmann** [comment]
As mentioned in #19, the ftp server does only allow 256 anonymous connections per hour. The general solution would be to try again later. It is working right now:

[ftp://mi.eng.cam.ac.uk/pub/mttt2/models/KittiSeg_pretrained.zip](ftp://mi.eng.cam.ac.uk/pub/mttt2/models/KittiSeg_pretrained.zip)

**Comment by heyulinxp** [comment]
Thank you very much. I still can't download this file now, no matter in windows or ubuntu. However, I can use train.py and the data to train a model, get these model files,and then use demo.py to evaluate. I'm happy about that.
