### ISSUE TITLE
Python2.7 or Python3.x to run the KittiSeg code

### ISSUE THREAD

**Issue by huaiyanggongzi** [MarvinTeichmann/KittiSeg#36]
Hi Marvin,

Would you like to let me know which `Python` version is required to run the `KittiSeg` code? In [this thread](https://github.com/MarvinTeichmann/KittiSeg/issues/8), @bendidi and @lemhell mention that Python 2.7 is supported. My development environment is Python 3.x, so I am curious to know whether I need to re-build the environment. 

Many Thanks!
Huaiyanggongzi

**Comment by WPSanberg** [comment]
My python3.5 environment gave me trouble, with python 2.7 it work directly (issue #35).

**Comment by huaiyanggongzi** [comment]
Hi WPSanberg,  thanks for the reply. By the way, my python development is Python 3.4.5. How did you let your Python 3.5 environment to support Python 2.7? Did you use virtualenv?I was trying to create a virtual environment under Python 3.4.5, which support 3.4.5 by default. Are there any setting I should take care when using virtualenv? Thanks.

**Comment by huaiyanggongzi** [comment]
Hi WPSanberg, one more question, I once read a notes mentioning that tensorflow1.0 GPU version only works under Python 2.7, is that right?

**Comment by WPSanberg** [comment]
Hi, I am using separate virtual environments for tensorflow with python 3.5 and 2.7, without any special settings or so that I am aware of... I do not know whether  tensorflow1.0 GPU is only compatible with python 2.7.

**Comment by MarvinTeichmann** [comment]
Python 2.7 works. 3.5 does not work right now. There seams to be an issue with commentjson. 

Modifing the code to be compatible with python 3.5 should not be a big issue and I am very happy to receive a pull request, if you made it work and tested. In KittiBox, the [pull request](https://github.com/MarvinTeichmann/KittiBox/commit/5ec5681981aa050a8c0e4d5853db50a6b5257e2a) introducing python 3.5 support only needed to change a couple of lines.
