### ISSUE TITLE
_load_gt_file too many values to unpack

### ISSUE THREAD

**Issue by StuvX** [MarvinTeichmann/KittiSeg#37]
I feel like a chump, but I have produced groundtruth images along with their natural counterparts and produced a train.txt and val.txt that appear to be the same format as the kittiseg versions. When I run train.py I get the following error:

  File "train.py", line 131, in <module>
    tf.app.run()
  File "/Users/wnas0001/anaconda3/envs/python2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 127, in main
    train.do_training(hypes)
  File "incl/tensorvision/train.py", line 393, in do_training
    modules['input'].start_enqueuing_threads(hypes, queue, 'train', sess)
  File "/../inputs/kitti_seg_input.py", line 355, in start_enqueuing_threads
    gen.next()
  File "/../inputs/kitti_seg_input.py", line 155, in _make_data_gen
    for image, gt_image in data:
  File "/../inputs/kitti_seg_input.py", line 114, in _load_gt_file
    image_file, gt_image_file = file.split(" ")
ValueError: too many values to unpack

I believe it has something to do with my txt file, which I've attached. Any help is greatly appreciated!
[train.txt](https://github.com/MarvinTeichmann/KittiSeg/files/918139/train.txt)

**Comment by MarvinTeichmann** [comment]
Yes, it seams to have to do with your data file. Maybe an extra new_line at the end of file? The error would happen, if there is a line with more then two white spaces. Try

`print(" File: {}".format(file))`

To see which throws the error line fails.

**Comment by StuvX** [comment]
Ah, yes there is something funny about the txt file I wrote in atom - I've simply edited your train3.txt and val3.txt files and it seems to work now.

**Comment by StuvX** [comment]
...although it ends and reports "Killed 9"...?
