### ISSUE TITLE
can't clone

### ISSUE THREAD

**Issue by BenMacKenzie** [MarvinTeichmann/KittiSeg#4]
_git clone git@github.com:MarvinTeichmann/KittiSeg.git_  fails:

"Please make sure you have the correct access rights
and the repository exists."

_git clone https://github.com/MarvinTeichmann/KittiSeg.git_

works fine.

however, _git submodule update --init --recursive_ 

then fails.

**Comment by amiltonwong** [comment]
See this [one](https://github.com/MarvinTeichmann/KittiSeg/issues/2)

**Comment by MarvinTeichmann** [comment]
The newest Version comes with `https` clone. So it should work out of the box for you. I do however still recommend `ssh`.
