### ISSUE TITLE
How to speed up predictions

### ISSUE THREAD

**Issue by jbrozena22** [MarvinTeichmann/KittiSeg#41]
I'm wondering if you have any ideas on how to speed up predictions. So far it's taking roughly a second per prediction, making it tough to get through large numbers (thousands) of images.

Would appreciate any thoughts you have!

**Comment by MarvinTeichmann** [comment]
The inference time is 24 images per second. This time is archived if the model is build once and images are feed one by one via feed_dict. This is done in `eval.py`. Don't use `demo.py` for large inference. Also see the discussion [here](https://github.com/MarvinTeichmann/KittiBox/issues/15).

For an even greater speed-up you could use queues and batch processing of inference images. Eval.py is written to simulate a real-time system which does not come with batch-processing.

**Comment by jbrozena22** [comment]
Thanks so much, that's very helpful. Also more generally, thank you for this amazing project.
