### ISSUE TITLE
Bug in gradient clipping?

### ISSUE THREAD

**Issue by dominikandreas** [MarvinTeichmann/KittiSeg#42]
gradient clipping in generic_optimizer.py results in the error "ValueError: No variables provided." 

issue and solution can be found here:
http://stackoverflow.com/questions/43210177/zip-object-for-opt-apply-gradients/43538898#43538898

edit: I used tensorflow 1.0.1

**Comment by MarvinTeichmann** [comment]
I did not come across this error. I would be very happy to receive a pull request, if you know more about this issue.

**Comment by dominikandreas** [comment]
I'm not sure why this error occurs at all, can't find anything wrong with the existing implementation. It might be a problem with windows / python3 implementation of tensorflow (what I'm using) and this project is compatible with neither (symbolic links and use of commentjson). I fixed the latter two locally and could submit a pull request if you'd like when I get around to it.

**Comment by leica8244** [comment]
I met the same problem and I am using python 3  on windows. Hope the problem can be fixed soon

**Comment by MarvinTeichmann** [comment]
Seams like a tensorflow/windows problem. Upgrading your OS Linux should fix this.
