### ISSUE TITLE
bug in download_data.py

### ISSUE THREAD

**Issue by daixiaogang** [MarvinTeichmann/KittiSeg#45]
the default  data_dir = "DATA",that is what I use. the vgg data is in 'DATA/vgg16.npy'.  But when decide whether to download the vgg data or not,you use vgg_weights = os.path.join(data_dir, 'weights', 'vgg16.npy'), which the folder is 'DATA/weights/vgg16.npy', this will cause redownload the vgg data again and agin(default: the data is stored in 'DATA/vgg16.npy')

**Comment by bendidi** [comment]
just create a subdir weights in DATA and put vgg16.npy in it

**Comment by daixiaogang** [comment]
OK， locatethe downloaded  ‘vgg16.npy’in file 'RUN/weights/'？
