### ISSUE TITLE
issues with python train.py --hypes hypes/KittiSeg.json

### ISSUE THREAD

**Issue by gopi77** [MarvinTeichmann/KittiSeg#46]
When i tried running python train.py --hypes hypes/KittiSeg.json, i got below error.

2017-04-30 17:29:56,186 ERROR File '/home/gopi/tensorflow/KittiSeg/hypes/../DATA/weights/vgg16.npy' not found. Download it from ftp://mi.eng.cam.ac.uk/pub/mttt2/models/vgg16.npy

Actually I see the vgg16.npy got downloaded into DATA folder along with data_road.zip during demo operation, do i need to manually copy this file into some other folder? the generated path "/hypes/../DATA/" looks like path join issue, please check it.

FYI , I could be able to run the python demo.py successfully using pre trained data.

**Comment by daixiaogang** [comment]
vgg16.npy must be in ../DATA/weights/vff16.npy

**Comment by lrthorita** [comment]
I also got this error when I tried to run "python demo.py --input_image data/demo/demo.png" ...

The error message that I got was this:
"2017-05-10 10:57:33,227 ERROR File 'DATA/vgg16.npy' not found. Download it from ftp://mi.eng.cam.ac.uk/pub/mttt2/models/vgg16.npy"

But I have downloaded  'vgg16.npy' and moved to 'DATA/vgg16.npy'. Does anyone have this same problem?

**Comment by bendidi** [comment]
if you just read the answer above you would see that "vgg16.npy must be in ../DATA/weights/vff16.npy" :-

**Comment by lrthorita** [comment]
I actually did it already. But I have just found out that, for some reason, the 'vgg16.npy' file was blocked. I tried to use chmod to change the permission, but it didn't work also. So, I just re-downloaded the file and moved to 'DATA/vgg16.npy', and it worked.

After all, I didn't have to move the file to '../DATA/weights/vgg16.npy' ...

But, thanks for your answer anyways.

**Comment by MarvinTeichmann** [comment]
Yeah, I should fix the whole location think soon.
