### ISSUE TITLE
plot MaxF1 and Average Precision like results in your paper

### ISSUE THREAD

**Issue by ChulhoonJang** [MarvinTeichmann/KittiSeg#47]
Dear Teichmann,

Most of all, Thank you for sharing your great work with us.

Now, I trained multi class segmentation with my own datasets and I found it works well.

To increase the segmentation result, I want to plot total maxF1 and average precision like figures 4 and 6 you added in your "MultiNet: Real-time Joint Semantic Reasoning for Autonomous Driving".

I saw all logs were saved in "output.log", but, it seems not to be a kind of good format for plotting.

Could you suggest efficient ways to plot the trainig result?

Secondly, which hyperparameters should be adjusted to improve the segmentation result?

Br,

**Comment by MarvinTeichmann** [comment]
Hi Br,

the output.log is in a very good format to be parsed by python code. You can find the script I am using for plotting [here](https://gist.github.com/MarvinTeichmann/e426bb74b4fd79259bd1a037de7b51e6).

**Comment by ChulhoonJang** [comment]
Hi,

Thank you for your reply. I will try!!
