### ISSUE TITLE
RGB images augmented with additional channels

### ISSUE THREAD

**Issue by eduardinjo** [MarvinTeichmann/KittiSeg#48]
I want to use images with RGB + additional input channels which have the same width and height as image. I thought of using same pretrained VGG network with additional weights in first layer corresponding to added channels. Required output is still binary segmentation mask.
Is this change feasible on your code? It seems to require delving in TensorVision backend?

**Comment by eduardinjo** [comment]
Forogt to mention. This was doable but required changing train.py in tensorvision, which defined image placeholder channel dimension.

**Comment by wenouyang** [comment]
Hi eduardinjo, would you like to elaborate what kind of modifications that you have made to let this solution handle images with more than 3 channels? Thanks.

**Comment by eduardinjo** [comment]
As stated you need to adapt input producer and CNN architecture file to produce inputs with more than 3 channels. + new weights for those inputs
Additionally in tensorvision source files you need to find instances that define input shape as only 3 channels. Check tensorvision core.py & train.py files
