### ISSUE TITLE
Could not import the submodules

### ISSUE THREAD

**Issue by zheshiyige** [MarvinTeichmann/KittiSeg#49]
Hi,
          I using the command line "git submodule update --init --recursive". Then run python demo.py --input_image data/demo/demo.png. It display the erros.

2017-05-08 10:15:15,383 ERROR Could not import the submodules.
2017-05-08 10:15:15,384 ERROR Please execute:'git submodule update --init --recursive'

Thanks and Best Regards,

**Comment by daixiaogang** [comment]
cd  KittiSeg
run shell git submodule update --init --recursive
you should initial submodule first

**Comment by MarvinTeichmann** [comment]
As stated in the error message: Please execute

`git submodule update --init --recursive`
