### ISSUE TITLE
How to do fast evaluate

### ISSUE THREAD

**Issue by JOOjinsoo** [MarvinTeichmann/KittiSeg#54]
Hello, I have started DeepLearning recently.
I'm really new in this field.
first of all, I really appreciate to learn this code.

This KittiSeg is really good for image segmentation.
However, It takes little bit long time to evaluate images.

Is there any method to evaluate fast?

**Comment by MarvinTeichmann** [comment]
Demo.py is not meant to evaluate the code. Use tv-analysis to perform evaluation. See also the code here: https://github.com/MarvinTeichmann/KittiBox/issues/15

**Comment by JOOjinsoo** [comment]
thanks! for the answer!!
