### ISSUE TITLE
Better way to share KittiSeg_pretrained.zip

### ISSUE THREAD

**Issue by zishanahmed08** [MarvinTeichmann/KittiSeg#55]
I have been constantly trying to download KittiSeg_pretrained.zip from ftp://129.169.82.147/pub/mttt2/models/KittiSeg_pretrained.zip. I have been trying every hour since the last couple of days.I already checked #19 #18 #33 . It is not the case that I forgot to unzip the file in the RUNS folder.

Can someone share their local copy via dropbox,google drive or any other method? My email id zishanahmed.08@gmail.com

**Comment by MarvinTeichmann** [comment]
I am happy if anybody uploads KittiSeg_pretrained somewhere else.

**Comment by Luxcy** [comment]
hi，do you have this file now？
I try many times, but fail.
Can you hlep me? 
Thank you~

**Comment by RyanHangZhou** [comment]
Hi, anybody has a copy of the pretrained model? I cannot download it either. Thx!

**Comment by xiaomofang** [comment]
> Hi, anybody has a copy of the pretrained model? I cannot download it either. Thx!

hi，do you have this file now？
I try many times, but fail.
If you've been successful, can you share a document with me, thank you

**Comment by xiaomofang** [comment]
> I am happy if anybody uploads KittiSeg_pretrained somewhere else.

Link：https://pan.baidu.com/s/1ZA78FWiWzGEFSPfyHtu4BQ 
Extract code：iz2v

**Comment by catalinpadurean** [comment]
> > I am happy if anybody uploads KittiSeg_pretrained somewhere else.
> 
> Link：https://pan.baidu.com/s/1ZA78FWiWzGEFSPfyHtu4BQ Extract code：iz2v

I can't access the link. Is it possible to upload it elsewhere? or to send the zip via email? my email si padurean_catalin@yahoo.com
