### ISSUE TITLE
reload previous model in a new training

### ISSUE THREAD

**Issue by jinhangw** [MarvinTeichmann/KittiSeg#56]
Hello,

I have a model trained with 500 images (Kitti data and ~200 images of my own). Now I want to add new images to improve this model. 
My question is, instead of re-train with all 520 images, can I reload this model and add 20 new images to re-train and improve this model? Maybe something like `saver = tf.train.import_meta_graph('my_test_model-1000.meta')` in tensorflow. How can I achieve it with minimal modification on train.py or tensorvision code?

Thank you very much!

**Comment by MarvinTeichmann** [comment]
Go to your logdir, increase max_iterations and use 'tv-continue' to continue training.

**Comment by jinhangw** [comment]
Thanks!
Do you mean hypes[solver][max_steps] and the continue_training(logdir) function in tensorvision.train? I'm still a bit confused about 'tv-continue'.

**Comment by StuvX** [comment]
I've successfully done what you're asking - in your RUNS folder there should be the saved model, go to model_files/hypes.json and increase max_iterations. Make sure that you have the new images referenced in your train.txt and val.txt files and that the hypes.json file points to these. Then to continue training use tv-continue --logdir RUNS/your_model_.

**Comment by StuvX** [comment]
Oh, if you haven't already make sure you follow Marvin's instructions for installing tensorvision that are toward the bottom of the intro page.

**Comment by jinhangw** [comment]
Thank you very much for your help!

**Comment by jk7g14** [comment]
thanks guys I could do what I wanted to do after seeing these answers.
