### ISSUE TITLE
Multiple classes e.g., lane markings?

### ISSUE THREAD

**Issue by villanuevab** [MarvinTeichmann/KittiSeg#58]
Hello! Thanks for sharing this awesome work. May I ask if the model is extensible to segment multiple classes? I see [here](https://github.com/MarvinTeichmann/KittiBox/issues/13) that KittiBox is not easily extensible to the case of multiple custom classes. Does the same go for the this module, too? I.e., is it the case that the segmentation submodule has classes road/not road; the bbox submodule has object/not object and it is difficult to extend these submodules to multiple classes?

**Comment by venuktan** [comment]
+1

**Comment by villanuevab** [comment]
Hm, looking at #29 it looks like a pretty involved process.

**Comment by MarvinTeichmann** [comment]
You need to follow the steps in #15. It shouldn't be that hard. If I understand it correctly several people made it work. I am happy to receive a pull request to make it.
