### ISSUE TITLE
How to use resnet?

### ISSUE THREAD

**Issue by daixiaogang** [MarvinTeichmann/KittiSeg#59]
Hi, Marvin. Thank you for your KittiSeg and the tutorial. I want to changge the vgg16 to resnet ,and the model has been downloaded ,but when I run train.py ,I met this error:
NotFoundError (see above for traceback): Tensor name "scale1/scale1/moving_mean/local_step" not found in checkpoint files DATA/weights/tensorflow_resnet/ResNet-L50.ckpt
Should I change some code?@MarvinTeichmann

**Comment by TJCVRS** [comment]
@daixiaogang Hi xiaogang i wonder if you solved this problem? Would you like to share your solution?

**Comment by daixiaogang** [comment]
@TJCVRS ，大兄弟，还没解决呢，不知道是不是代码的问题，这可是我的毕设啊，解决了教教我

**Comment by MarvinTeichmann** [comment]
For reference, the weights can be found [here](ftp://mi.eng.cam.ac.uk/pub/mttt2/models/tensorflow_resnet/).

**Comment by liuzhisheng1226** [comment]
@MarvinTeichmann The websites can't be visited

**Comment by bbidong** [comment]
@daixiaogang 大兄弟，我是今年的毕设啊，能问问你训练出的ResNet模型效果比VGG的好麽？？

**Comment by daixiaogang** [comment]
大兄弟，我很早之前放弃这个了，不过我觉得，kitti那几百张数据太少了，不知道你有没有其他的数据，残差网络效果应该要比vgg好，而且更快

**Comment by bbidong** [comment]
哈哈谢谢大兄弟咯，我训练出来了，待会在kitti测试集上测评一下

**Comment by daixiaogang** [comment]
good

**Comment by xxxy-931231** [comment]
@bbidong   你好 可以告诉我怎么训练resnet101吗（我不知道在哪里下载数据和下载完后应该怎么训练） 谢谢！！！ 我微信15521179117（如果可以加微信更好） 再次感谢！！！！
