### ISSUE TITLE
Training on Multiple GPUs

### ISSUE THREAD

**Issue by wolewomada** [MarvinTeichmann/KittiSeg#73]
Hi Marvin,

Thanks for sharing the nice work. 

I am wondering if there is a way to train the model on more one GPUs. If so, I could not find the parameter to define the number of GPUs that I can use. Thank you for your answer.

**Comment by MarvinTeichmann** [comment]
Yes, follow this [example](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py).

Speed-wise it is usually better to run multiple runs in parallel then do one run on multiple gpus.

**Comment by chamcham115** [comment]
@MarvinTeichmann 
Hello, Marvin. Thanks for your comment. 
But, I wonder how to fix the code.
your code can execute on multiple gpu. 

But, I cannot use pull performance. 
It just use the whole memory on gpu ( I have 4 gpu )
But, It use two gpus. so remained gpus does not running. 

I think this example  can use whole gpus. 
But how to fix the code in your code on tensorvision. 

Thanks.
