### ISSUE TITLE
training with Resnet 

### ISSUE THREAD

**Issue by bendidi** [MarvinTeichmann/KittiSeg#75]
Hello, 

I've tried to train the network with resnet as encoder , I've downloaded the weighs from here : 

[link](https://github.com/tensorflow/models/tree/master/slim)

but I get this error : 
```
NotFoundError (see above for traceback): Tensor name "scale2/block2/b/beta" not found in checkpoint files DATA/weights/resnet_v1_101.ckpt
	 [[Node: save_1/RestoreV2_54 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_54/tensor_names, save_1/RestoreV2_54/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_479/_483 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_5135_save_1/RestoreV2_479", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

```

So we might be using two different checkpoints , is it possible to share you share your checkpoint file that you used for this part ?

thanks !

**Comment by MarvinTeichmann** [comment]
I have uploaded my weights [here](ftp://mi.eng.cam.ac.uk/pub/mttt2/models/tensorflow_resnet/).

**Comment by bendidi** [comment]
Thanks !

**Comment by liuzhisheng1226** [comment]
@MarvinTeichmann Your link can't be visited..

**Comment by shipengai** [comment]
@bendidi Did you success to training it with Resnet as encoder? which dataset? how about the performance of training result?
