### ISSUE TITLE
increase descriptions of input files for us lay people 

### ISSUE THREAD

**Issue by Steven-N-Hart** [MarvinTeichmann/KittiSeg#8]
Could you perhaps provide a description of `val3.txt` and `train3.txt`? For instance, is the file nomenclature somehow significant? 

It is not entirely clear on how one would make their own training images.

I looked at the examples in TensorVision, but it too does not really explain what the masks are.  It just labels them GT:
```[
    {
        "raw": "/home/moose/GitHub/MediSeg/DATA/OP1/img_00.png",
        "mask": "/home/moose/GitHub/MediSeg/DATA/OP1/img_00_GT.png"
    },
    {
        "raw": "/home/moose/GitHub/MediSeg/DATA/OP1/img_01.png",
        "mask": "/home/moose/GitHub/MediSeg/DATA/OP1/img_01_GT.png"
    },
    {
        "raw": "/home/moose/GitHub/MediSeg/DATA/OP1/img_02.png",
        "mask": "/home/moose/GitHub/MediSeg/DATA/OP1/img_02_GT.png
}
]
```
THANKS

**Comment by kyoseoksong** [comment]
I would like to know how I can structure my own datasets, too. 
Can you elaborate on it, please?

**Comment by MarvinTeichmann** [comment]
An example of a  `val3.txt` and `train3.txt` can be found in `data`.  Each line of those files contains pathes to two images. The first image is the input image and the second the ground_truth image. Both pathes are seperated with a withe space. The paths are given relative to the location of the .txt file.

Hope this helps!

**Comment by Steven-N-Hart** [comment]
OK. I think I understand a bit more now, and will elaborate here so that when I forget, I can just come back :). 
The `train3.txt` file is a space-separated file with column 1 being the path to an image and column 2 to a mask.  The mask file is a re-colored version of the image in column 1, with colors indicated by what the user inputs into `KittiSeg.json` in the data section:
```
"road_color" : [255,0,255],
"background_color" : [255,0,0],
```
`train3.txt` is a list of image pairs for training
`val3.txt` is a list of image pairs for validation

So, if one wants to train KittiSeg on their own data, they must create the image masks on their own images, and remove the references to the road data.

Does this sound about right?

**Comment by MarvinTeichmann** [comment]
That sounds about right. I would usually call the second image `ground_truth` or `label`.

**Comment by MarvinTeichmann** [comment]
I have created [input.md](https://github.com/MarvinTeichmann/KittiSeg/blob/master/inputs/inputs.md), which is supposed to describing the input format in detail. Feel free to modify this file or add details if you feel this is needed for better understandability. As author it is sometime hard to see what aspects are obvious ;).

**Comment by MarvinTeichmann** [comment]
Providing [input.md](https://github.com/MarvinTeichmann/KittiSeg/blob/master/inputs/inputs.md) should also fix this issue :).

**Comment by kyoseoksong** [comment]
Hello Marvin,

Thanks for the explanation on inputs.md!

Fortunately, my classification problem is binary one, so I think I can take
advantage of "Easy way"
Besides two things you mentioned in the article, isn't there anything I
have to modify, or fix any codes?
I just wonder if I can just use the same file like kitti_seg_input.py,
kitti_eval.py for my problem.

I am a kind of novice, so please bear with me.

Thanks in advance, Marvin.

Andy

**Comment by MarvinTeichmann** [comment]
Hi  kyoseoksong,

are you doing classification or segmentation? The code is build for segmentation, which is basically "classification per pixel". If you are solving segmentation, you can use the code as given, including  `kitti_seg_input.py` and `kitti_eval.py`. Just make sure, that you set `road_color` and `background_color` correctly. 

`kitti_eval.py` will compute the scores of the kitti benchmark (maxF1 and averagePrecision). If you have your own dataset which comes with different metrics you might want to implement you own evaluation code. But this does not influence training, first make sure that it is running as is.

If you are actually doing classification, you need to write your own input producer, loss function and evaluate for classification. This is not to difficult, but takes some hand-tuning. I did write an[ input producer for classification](https://github.com/TensorVision/TensorVision/blob/master/examples/inputs/generic_input.py) at some point. Having said this, this file is most likely not compatible anymore with the current tensorvision/tensorflow version. It might however be a good starting point. Classification input is not that different from segmentation input. So we are talking about minor adjustments.

**Comment by kyoseoksong** [comment]
I am doing segmentation, Marvin. 

Maybe I should just modify the RGB to black and white according to my ground truth images. I have lung CT scan images and masks. Now I think I grasp the concept. Thanks for your reply, and I will try this today, and get back to you, I expect, with a good result. I hope many people know and use your code cause it's so cool. 

Thanks,
Kyoseok

2017. 2. 17. 오후 8:56 Marvin Teichmann <notifications@github.com> 작성:

**Comment by MarvinTeichmann** [comment]
Happy to help. Don't forget to cite one of my papers, if you get any chance ;). 

Since  f7fdb24, using greyscale images work out-of-the box. The images will be converted to RGB upon load, so a black pixel has value [0,0,0], white [255,255,255] and some light grey can will be [200, 200, 200].

**Comment by kyoseoksong** [comment]
Hi Marvin,
I tried to read your inputs.md again, but I coundn't reach there. Any
reason to get rid of it?
https://github.com/MarvinTeichmann/KittiSeg/blob/master/inputs/inputs.md

Thanks,
Andy

On Fri, Feb 17, 2017 at 10:23 PM, Marvin Teichmann <notifications@github.com

**Comment by MarvinTeichmann** [comment]
Hi Andy,

commit 0e8d54876492f8fff25ffe05df430f50e0b3fbf2 moved it to [docu/inputs.md](https://github.com/MarvinTeichmann/KittiSeg/blob/master/docu/inputs.md). 

Marvin

**Comment by kyoseoksong** [comment]
All right. 

Thanks, Marvin. 

2017. 2. 19. 오후 7:15 Marvin Teichmann <notifications@github.com> 작성:

**Comment by lemhell** [comment]
Hello, @MarvinTeichmann 
I want to train this model on my own dataset.
I created the necessary files train_file and val_file, specified road_color and background_color.
But when I call tv-train --hypes myHype.json, the output is:
ERROR Data URL for Kitti Data not provided.                                                                 
ERROR Please visit: http://www.cvlibs.net/download.php?file=data_road.zip                                   
ERROR and request Kitti Download link.                                                                      
ERROR Enter URL in hypes/kittiSeg.json

I'm downloading this data right now (got link by e-mail and started tv-train again), but I don't see, why do I need it to train on my own data, or maybe I just did something wrong. Can you help me?
Thank you in advance.

**Comment by bendidi** [comment]
I believe you should comment the line 127 in the script train.py  , that's the line responsible for downloading the dataset, after commenting it it will just use directly the path's that you provided on the hypes for your own data

**Comment by lemhell** [comment]
Thank you, for your response, @bendidi @MarvinTeichmann 
Are you sure that I should comment this line?
First of all, I'm using tv-train, not train.py (but maybe tv-train calls train.py)
Secondly, line 127 is `train.do_training(hypes)`, looks like it is connected to the training, not to the download process. Haven't tested this yet, though.

**Comment by bendidi** [comment]
yes it's the 123 rd line ,sorry about that , I added some lines in my script that I forgot about , if you made your input configuration correctly , it should work now

**Comment by lemhell** [comment]
@bendidi Thank you for the clarification. 
All I did: 
created my train.txt and val.txt with the following structure:
path_to_img/img1.jpg path_to_mask/mask1.png
And so on.
Then, I copied the hype file and changed paths in it for train_file and val_file and changed road_color and background_color accordingly.
Then, I commented line 123 and changed one import from commentjson to json (It was returning the same error, as [Issue 28](https://github.com/MarvinTeichmann/KittiSeg/issues/28)).
After that, I'm starting this:
`python train.py --hypes hypes/MyHype.json`
And get the same error, as in [Issue 35](https://github.com/MarvinTeichmann/KittiSeg/issues/35)

Have you done something differently in order to train this model on your custom data?
Also, my images are 3D and masks are 2D, but I've seen somewhere in the issues that this should work just fine.

**Comment by bendidi** [comment]
I've done something different , I completely changed the input script , so that I just have to give it a path , and it loads the images directly without the need of train.txt and val.txt , I also added a line to resize images to the same shape as kitti images , the images and the masks should be  'RGB' I believe (I don't know what you mean by 3D and 2D ) 
for 2 colors I got it working just fine with this setup , and the result was satisfying for the most part , hope it helps you

**Comment by lemhell** [comment]
By the input script you mean "input_file" field inside the hypes json? By default it's this one: "../inputs/kitti_seg_input.py"
If I understand you correctly, you did not changed anything beside that "input_file" script.
By 3D I meant RGB and by 2D - grayscale images.

**Comment by bendidi** [comment]
yes it's the kitti_seg_input.py script , 

The problem might be because you use grayscale images for the mask , and the image reader reads them in RGB mode as seen in line [123](https://github.com/MarvinTeichmann/KittiSeg/blob/master/inputs/kitti_seg_input.py#L123) of the input file and so it won't find the colors that you provided in the hypes file , to create the training variables , lines [157](https://github.com/MarvinTeichmann/KittiSeg/blob/master/inputs/kitti_seg_input.py#L157) and [158](https://github.com/MarvinTeichmann/KittiSeg/blob/master/inputs/kitti_seg_input.py#L158)

**Comment by lemhell** [comment]
I changed the masks to be in RGB as well, but the problem persists: `ValueError: No variables provided.`
Do you have any code so I could compare? 
Also, did you have the problem with inability to [import dump from commentjson](https://github.com/MarvinTeichmann/KittiSeg/issues/28)?

**Comment by bendidi** [comment]
nope , commentjson worked fine , I'm running it on python2.7 , maybe that's why  
I don't have the code right , (on another computer , so till monday , if you would still need it )

when you changed the masks to be in RGB , did you make sure the 2 colors that are in in RGB  mask are the ones you provided in the hypes ? aside from that I cannot think of anything else ...

**Comment by lemhell** [comment]
@bendidi 
Thank you for your answers. 
I installed everything for Python 2.7 and it started to work, even with `commentjson`.

**Comment by lemhell** [comment]
I started training and MaxF1 started near 17, now it is near 26 after 4500 steps (out of 12000) and sometimes jumps around. Is it ok or should I do something? 
Also, there is a parameter called weight_loss and it is always the same: 3.62.

**Comment by KKayak** [comment]
@lemhell how to comment line 123

**Comment by lemhell** [comment]
@1464256670 
If I recall correctly, I downloaded this repository and commented the problematic line (123) in the train.py script (using `#` at the start of this line). 
However, it did not resolve the problem and I switched to Python 2.7. After that, the script started to work.

**Comment by KKayak** [comment]
@lemhell by the way,thanks for your replyment,another question:to train my own data,all what i did is creating my train.txt and val.txt ,is that enough ,anything else to do?

**Comment by 1464256670** [comment]
is only running train.py enough,any other .py should i run?

**Comment by KKayak** [comment]
@lemhell is only running train.py enough,any other .py should i run?

**Comment by lemhell** [comment]
@1464256670 
You can probably find some info [here](https://github.com/MarvinTeichmann/KittiSeg/blob/master/docu/inputs.md).

**Comment by YongKun-Liu** [comment]
objective function also need to change
