### ISSUE TITLE
Functionality of "calib_" folder's files 

### ISSUE THREAD

**Issue by wolewomada** [MarvinTeichmann/KittiSeg#82]
Marvin,

Thank you for your excellent work which has been one of the most well performed models I have seen. I have been using your model to successfully predict segmentation works. 

One thing I could not figure out is that there is one folder called "calib_" within training and testing folders. I do not see where the model is using those files in calib_. Could you please let me know what is the functionality of these files used for? and is that necessary for me to modify these files when I am training my own dataset? if so, how to deploy these modifications? 

Thank you very much for your time.

Best regards,
Peter

**Comment by MarvinTeichmann** [comment]
Calib contains calibration parameters for the Camera used to make the images. I do not use calib inside my code. Look at the kitti documentation for more information regarding calib.
