### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by wolewomada** [MarvinTeichmann/KittiSeg#83]
Hi, Marvin or folks,

Has anyone met the following running errors while training on own dataset?   I have successfully trained and predicted my owner dataset. However, this error shown below happens sometime when I add extra training images. It is also strange that sometime the code runs properly even with extra added images. Is that caused by the title of added images? not sure. Appreciate your help and answer for what could be reason causing this error and how to fix it. Thank you!

![image](https://user-images.githubusercontent.com/26074121/28049523-96e82c84-65bd-11e7-9e0e-08921dea9f09.png)

**Comment by XononoX** [comment]
I'm experiencing this same issue. Can you please explain what was causing it and how you fixed it?
