### ISSUE TITLE
Why threshold vector has 256 values?

### ISSUE THREAD

**Issue by kalanityL** [MarvinTeichmann/KittiSeg#84]
Hi,

If I understand correctly the evaluation process, threshold (file seg_utils) is a vector of different values for possible threshold between 0 and 1 and we get all the results for all these possible threshold and get in the "index" variable the value for the best threshold. 
Is this correct? 
Is the size of the vector (256) meaning full ? or could if be any random lengh? 
(for instance could it be [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]

TIA for the help :) 
K.

**Comment by MarvinTeichmann** [comment]
This is the evaluation code provided by the Kitti Segmentation benchmark. Please address this question to [andreas geiger](https://avg.is.tuebingen.mpg.de/person/ageiger).
