### ISSUE TITLE
how can I know when I feed a image into the model ,how can I know if there is a higway or minor street?

### ISSUE THREAD

**Issue by jacobishao** [MarvinTeichmann/KittiSeg#86]
how can I know when I feed a image into the model ,how can I know if there is a highway or minor street?
I don't know how to operate it in the source code ? Can you give me some guidance?

**Comment by MarvinTeichmann** [comment]
This is a different project. See [here](https://github.com/MarvinTeichmann/KittiClass)

**Comment by jacobishao** [comment]
you are so kind ! thank you very much!

2017-07-21 0:45 GMT+08:00 Marvin Teichmann <notifications@github.com>:
