### ISSUE TITLE
which output file can be used as the weights?

### ISSUE THREAD

**Issue by xiangcong** [MarvinTeichmann/KittiSeg#87]
First thanks for the great codes!
I trained the model on my own data, and get the following output files:
model.ckpt-199.data-00000-of-00001
model.ckpt-199.index
model.ckpt-199.meta

I think model.ckpt-199.data-00000-of-00001 maybe the one, and I replace the model.ckpt-15999 with it, and then rename to "model.ckpt-15999".

However when I run the python demo.py, it says wrong format.
Is there any one can help me?

**Comment by bendidi** [comment]
i believe these outputs the you get are stored in a folder called "RUNS/Runs-xxxxxxxxx/" just give the path to the whole folder as the model, tensorflow will load them automatically

**Comment by xiangcong** [comment]
Thanks for @bendidi ~!
