### ISSUE TITLE
Testing On Other Image Sets

### ISSUE THREAD

**Issue by davidgroden** [MarvinTeichmann/KittiSeg#90]
Hey Marvin,

Thank you so much for sharing your code. When I run KittiSeg on the Kitti dataset, the segmentation is able to find the road to the precision you posted. But when I try to run KittiSeg on images from other datasets like CITYSCAPES, the network is either not able to detect any road segmentation or just the left edge. I don't see any image filtering on the input image before running the tf session in the demo.py. Any ideas why there would be such a big difference in performance?

Best,
David

**Comment by MarvinTeichmann** [comment]
Yes, the cityscapes images are statistically very different from the Kitti Data. You will need to train the network using Cityscapes data, if you want meaningful results. If this is not an option, you need to do at least perform some kind of [domain adaptation](https://arxiv.org/abs/1702.05464) before using different data. This is however a different field of research.

**Comment by davidgroden** [comment]
Great, thanks for your response. Do you by chance have results from training and evaluating KittiSeg on other datasets or using a domain adaption?

**Comment by MarvinTeichmann** [comment]
I got around 98% iou by training on cityscapes data.

**Comment by davidgroden** [comment]
Great, thanks for your response.

**Comment by davidgroden** [comment]
Is there any chance you could share the CityScapes trained model?

**Comment by MarvinTeichmann** [comment]
Did the experiments quite a while ago. The scripts won't work out of the box and are not compatible with the current code base. So I think it would be much easier if you just implemented a cityscapes data loader yourself.
