### ISSUE TITLE
Test on new image from trained model

### ISSUE THREAD

**Issue by wolewomada** [MarvinTeichmann/KittiSeg#91]
Hi Marvin or folks,

I have successfully trained Kittiseg model and would like to use the trained model to test on some new images. The way to evaluate new images is to use tv-analyze --logdir PATH/TO/RUNDIR which will evaluate the images directory listed in the val3.txt file. However, in order to get the command run, I have to provide the corresponding ground true directory in the val3.txt following image directory. I am wondering if this is correct way to test on new image by using trained model. Thank you very much.

Best regards,
Peter

**Comment by bendidi** [comment]
here is part of the code I'm using for prediction : 

```
.....

logdir = path/to/trained/model/

hypes = tv_utils.load_hypes_from_logdir(logdir, base_path='hypes')
logging.info("Hypes loaded successfully.")
# Loading tv modules (encoder.py, decoder.py, eval.py) from logdir
modules = tv_utils.load_modules_from_logdir(logdir)
logging.info("Modules loaded successfully. Starting to build tf graph.")
# Create tf graph and build module.
with tf.Graph().as_default():
        # Create placeholder for input
        image_pl = tf.placeholder(tf.float32)
        image = tf.expand_dims(image_pl, 0)
        # build Tensorflow graph using the model from logdir
        prediction = core.build_inference_graph(hypes, modules,
                                                image=image)
        logging.info("Graph build successfully.")
        # Create a session for running Ops on the Graph.
        sess = tf.Session()
        saver = tf.train.Saver()
        # Load weights from logdir
        core.load_weights(logdir, sess, saver)
        logging.info("Weights loaded successfully.")
num_classes = hypes['arch']['num_classes']
image_height = hypes['jitter']['image_height']
image_width = hypes['jitter']['image_width']
softmax = prediction['softmax']

image = scp.misc.imread(   Path/to/Image ,mode='RGB')
feed = {image_pl: image}
output = sess.run([softmax], feed_dict=feed)
output = output[0].reshape(image_height, image_width,num_classes)
output_image = np.argmax(output_image,axis=2)
......
```
hope it helps !

**Comment by kalanityL** [comment]
@wolewomada 
You can generate the corresponding DATA/data_road/testing.txt file with your list of image paths
and run 
(from evaluation import kitti_test)
kitti_test.do_inference

**Comment by wolewomada** [comment]
@bendidi Sorry for response in delay. Thank you very much for your help. I appreciate it!

**Comment by wolewomada** [comment]
@kalanityL Sorry for response in delay. Thank you very much for your answer. I appreciate it!
