### ISSUE TITLE
prediction with resnet

### ISSUE THREAD

**Issue by jk7g14** [MarvinTeichmann/KittiSeg#96]
I used demo.py with my own trained resnet weights.

but I got this error

**Comment by jk7g14** [comment]
I added shape in placeholder and it solved it.

**Comment by chamcham115** [comment]
hello, I have a question. 
I met the same error message. 
Can I know how to fix it?

**Comment by kalanityL** [comment]
@jk7g14  could you detail what line you changed?

**Comment by jk7g14** [comment]
Oh, I just changed this line


image_pl = tf.placeholder(tf.float32)

to

image_pl = tf.placeholder(tf.float32,shape=(480,640,3))

The shape is the images' shape that I trained during the training.

**Comment by jk7g14** [comment]
Oh, I just changed this line


image_pl = tf.placeholder(tf.float32)

to

image_pl = tf.placeholder(tf.float32,shape=(480,640,3))

the shape is images' shape that I trained during the training.

**Comment by jk7g14** [comment]
Oh, I just changed this line


image_pl = tf.placeholder(tf.float32)

to

image_pl = tf.placeholder(tf.float32,shape=(480,640,3))

the shape is images' shape that I trained during the training.

**Comment by bbidong** [comment]
@jk7g14  I train the ResNet model ,but the output of demo.py is the same as input  without any segmentation ,can you give me a hand?
