### ISSUE TITLE
_make_data_gen() and start_enqueueing_threads()

### ISSUE THREAD

**Issue by villanuevab** [MarvinTeichmann/KittiSeg#98]
I'm not sure I understand what is happening in `inputs/kitti_seg_input.py` here: https://github.com/MarvinTeichmann/KittiSeg/blob/master/inputs/kitti_seg_input.py#L169-L173. 
```        
elif phase == 'train':
    yield jitter_input(hypes, image, gt_image)
    yield jitter_input(hypes, np.fliplr(image), np.fliplr(gt_image))
```
So, we are yielding 2 generators to the variable, `gen`, in L359: 
```
gen = _make_data_gen(hypes, phase, data_dir)
gen.next() # but then why do we just iterate over it? 
```
But then why do we do the `gen.next()` in the following line, without making use of the returned value? What is the purpose of this portion of the code, in `start_enqueueing_threads()`?

**Comment by MarvinTeichmann** [comment]
Your assumption, that the second statement [@L173](https://github.com/MarvinTeichmann/KittiSeg/blob/master/inputs/kitti_seg_input.py#L173) will never be reached is wrong. 

The generator created by `yield` will jump back to the last yield keyword and execute the remainder of the function from there, pausing at the next `yield` command. You can test this behaviour using the minimal example below.  

```        
In [3]: def mygen():
   ...:     while True:
   ...:         yield 0
   ...:         yield 1
   ...:         
In [4]: gen = mygen()
In [5]: gen.next()
Out[5]: 0
In [6]: gen.next()
Out[6]: 1
In [7]: gen.next()
Out[7]: 0
In [8]: gen.next()
Out[8]: 1
```

**Comment by villanuevab** [comment]
Ah, yes. A quick review of yield statements and your response showed me that I was wrong. Thank you!

**Comment by villanuevab** [comment]
Does this mean that the dataset is effectively doubled during training? In particular, that there are two versions of the input image in the training data: 
1. the input image itself, and,
2. a horizontally flipped copy of the input image

**Comment by MarvinTeichmann** [comment]
Yes, data augmentation like random flipping is used to increasing the amount of effectively available training data.

Other forms of data augmentation applied is random aspect ratio augmentation (random resize, random crop) and color augmentation (random brightness, random contrast, random saturation and random hue).

**Comment by wenouyang** [comment]
Hi Marvin, related to random resize or random crop, does that mean you the training set will have different image size when feeding to the network input?

**Comment by MarvinTeichmann** [comment]
If you use `batch_size = 1` (default) you can train the network with variable image sizes (default and recommended).

For batch_sizes > 1 all inputs need the same size. That can be achieved by setting `reseize_image` or `crop_patch` to true. Resize_image will perform bilinear resize _after_ the augmentation (if you use both random resize and random crop this means that still meaningful augmentation is done) . `crop_patch` will crop a random patch of fixed size on the image.
